// Generated by https://quicktype.io

class Employee {
  int id;
  String firstName;
  String lastName;
  String email;
  int vacationDateCount;

  Employee({
    this.id,
    this.firstName,
    this.lastName,
    this.email,
    this.vacationDateCount,
  });
}
