import 'package:json_annotation/json_annotation.dart';

part 'user.g.dart';

// Generated by https://quicktype.io
@JsonSerializable(nullable: false)
class User {
  int id;
  String firstName;
  String lastName;
  String email;
  int vacationDateCount;
  int roleId;

  User(
      {this.id,
      this.firstName,
      this.lastName,
      this.email,
      this.vacationDateCount,
      this.roleId});

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);

  Map<String, dynamic> toJson() => _$UserToJson(this);

  get fullName => "${this.firstName} ${this.lastName}";
}
