// Generated by https://quicktype.io

import 'package:employeetracker/model/user.dart';
import 'package:json_annotation/json_annotation.dart';

import 'enum/vacation-status.enum.dart';

part 'vacation-request.g.dart';

@JsonSerializable(nullable: false)
class VacationRequest {
  int id;
  int userId;
  VacationStatus status;
  String description;
  DateTime startDate;
  DateTime endDate;
  User user;

  VacationRequest(
      {this.id,
      this.userId,
      this.status,
      this.description,
      this.startDate,
      this.endDate,
      this.user});

  factory VacationRequest.fromJson(Map<String, dynamic> json) =>
      _$VacationRequestFromJson(json);

  Map<String, dynamic> toJson() => _$VacationRequestToJson(this);
}

class VacationRequestParameter {
  int vacationRequestId;
  VacationStatus vacationStatus;

  VacationRequestParameter({this.vacationRequestId, this.vacationStatus});

  Map<String, dynamic> toJson() => <String, dynamic>{
        'vacationRequestId': this.vacationRequestId,
        'vacationStatus': this.vacationStatus.index,
      };
}
