// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

import 'enum/vacation-status.enum.dart';

part 'vacation-request.g.dart';

@JsonSerializable(nullable: false)
class VacationRequest {
  int id;
  int userId;
  VacationStatus status;
  String description;
  DateTime startDate;
  DateTime endDate;

  VacationRequest({
    this.id,
    this.userId,
    this.status,
    this.description,
    this.startDate,
    this.endDate,
  });

  factory VacationRequest.fromJson(Map<String, dynamic> json) =>
      _$VacationRequestFromJson(json);

  Map<String, dynamic> toJson() => _$VacationRequestToJson(this);
}
